title: LuxAgent
description: The Autonomous Workforce for Silicon Photonics
url: "https://heydarid.github.io" # Replace with your actual GitHub username
baseurl: "/luxweb"             # Your repo name

# Use the remote theme plugin
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Plugins required for this theme
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
minimal_mistakes_skin: "dark" # "neon" or "aqua" also look great for photonics!